#!/bin/bash

cd /home/vagrant
git clone https://github.com/holgerBerger/hpc-workspace-v2
cd hpc-workspace-v2
git pull
rm -rf build
cd ..
echo .......................................
echo ...debug build.........................
echo .......................................
cd hpc-workspace-v2/;  cmake --preset debug-ninja -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld"; cmake --build --preset debug -j; sudo cp build/debug/bin/ws_restore buil
bug/bin/ws_restore_notest

echo .......................................
echo ...unit tests..........................
echo .......................................
#cd hpc-workspace-v2 
ctest --preset debug .

cd
echo .......................................
echo ...release build.......................
echo .......................................
cd hpc-workspace-v2/; cmake --preset release-ninja -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld"; cmake --build --preset release -j; sudo cp build/release/bin/ws_restore build/release/bin/ws_restore_notest
echo .......................................

